### ISSUE TITLE
unclear login in "block tag latest for images #7"

### ISSUE THREAD

**Issue by tommeramber** [openshift-4-compliance/openshift-4-compliance-automation#14]
I can't seem to understand who this policy works, and why it is under "block tag latest for images" and not "modification prevention of default SCCs"?

@igorkchyts Let's sit on this one together, I've talked with @michaelkotelnikov about it and he didn't remember when or why he merged that one.

**Comment by michaelkotelnikov** [comment]
Refereed PR at - https://github.com/openshift-4-compliance/openshift-4-compliance-automation/pull/7

**Comment by michaelkotelnikov** [comment]
Commits were not pushed to repository. They are present in @igorkchyts commit history, but they were never pushed to the master branch.
