### ISSUE TITLE
Do not allow unwanted SA to be paired with privileged scc

### ISSUE THREAD

**Issue by igorkchyts** [openshift-4-compliance/openshift-4-compliance-automation#20]
@michaelkotelnikov 
The rules currently disables adding new users by looking at 'privilged scc' object and blocking from adding new SA. 
In Openshift 4.6 this policy does not work because SA that has been paired with SCC like 'privileged' will be included in relating clusterrolebinding instead of the scc object itself.

**Comment by michaelkotelnikov** [comment]
Merged fix.
