### ISSUE TITLE
Gatekeeper OAuth secured identityProviders only - ACM

### ISSUE THREAD

**Issue by tommeramber** [openshift-4-compliance/openshift-4-compliance-automation#82]
### Description
The policy ensures that only secured identityProviders (based on a dynamic, customizable list from the constraint object) are allowed on the cluster. 

### Policy Category
Security & Best Practice

### Rational
There are multiple identity provider types for openshift cluster, and some are more secure than others (e.g. OpenID connect is much more secure than Basic Auth). This policy is designed to enable cluster administrators to verify that only allowed (secured) types are configurable on the cluster.
 
### Policy Enforcement
The policy makes sure that the two gatekeeper objects - `constraint` and `constrainttemplate`, that the policy is comprised of does exist on the managed cluster; Once they are, it verifies that the constraint object of type `k8soauthsecuredidentityprovidersonly` does not include any violations (`totalViolations == 0`) as indication that the OAuth object indeed includes only approved Identity Providers

**Comment by michaelkotelnikov** [comment]
Done and merged at https://github.com/openshift-4-compliance/openshift-4-compliance-automation/pull/81
