### ISSUE TITLE
Several policies in redhat-acm README resolves with 404 error

### ISSUE THREAD

**Issue by igorkchyts** [openshift-4-compliance/openshift-4-compliance-automation#90]
### Description
Can't resolve several policies:
disallowed-role-policy , role-policy, role-binding-policy, gatekeeper-disalllow-privileged-scc-usage, restricted-scc-validation-policy 

### Steps to reproduce
Choose one of the policies in the README file of redhat-acm

### Expected behavior
Redirect to chosen policy 

### Actual behavior
404 error, page missing

### Versions
Github

**Comment by michaelkotelnikov** [comment]
Fixed.
